// Generated by CoffeeScript 1.4.0
(function() {
  var Api, Classifier, TopBar, User, api, classifier, topBar, _ref;

  if ((_ref = window.app) == null) {
    window.app = {};
  }

  Api = zooniverse.Api;

  api = new Api({
    project: "radio"
  });

  TopBar = zooniverse.controllers.TopBar;

  topBar = new TopBar;

  topBar.el.appendTo(document.body);

  Classifier = app.controllers.Classifier;

  classifier = new Classifier;

  classifier.el.appendTo(document.body);

  User = zooniverse.models.User;

  User.fetch();

  window.app.main = {
    api: api,
    topBar: topBar,
    classifier: classifier
  };

  $(document).ready(function() {
    var ir_r_set, slide_lines;
    ir_r_set = function(fore_opacity) {
      return $(".radio--wizard--viewer--image__fore").css({
        opacity: fore_opacity
      });
    };
    slide_lines = $(".radio--wizard--slide");
    slide_lines.on("mousedown", function(e) {
      var $this, position, x_fraction, x_offset;
      $(this).data("mouse_is_down", true);
      $this = $(this).children(".radio--wizard--slide--line");
      position = $this.offset();
      x_offset = e.pageX - position.left;
      x_fraction = parseFloat(x_offset) / parseFloat($this.width());
      if (x_fraction > 1) {
        x_fraction = 1;
      } else if (x_fraction < 0) {
        x_fraction = 0;
      }
      x_offset = x_fraction * parseFloat($this.width());
      $this.children(".radio--wizard--slide--dot").css({
        left: x_offset
      });
      return ir_r_set(1.0 - x_fraction);
    });
    $("body").on("mouseup", function(e) {
      return slide_lines.data("mouse_is_down", false);
    });
    return slide_lines.on("mousemove", function(e) {
      var $this, position, x_fraction, x_offset;
      console.log(".radio--wizard--slide--line, mousemove");
      if ($(this).data("mouse_is_down") !== true) {
        return;
      }
      $this = $(this).children(".radio--wizard--slide--line");
      position = $this.offset();
      x_offset = e.pageX - position.left;
      x_fraction = parseFloat(x_offset) / parseFloat($this.width());
      if (x_fraction > 1) {
        x_fraction = 1;
      } else if (x_fraction < 0) {
        x_fraction = 0;
      }
      x_offset = x_fraction * parseFloat($this.width());
      $this.children(".radio--wizard--slide--dot").css({
        left: x_offset
      });
      console.log("x_fraction = " + x_fraction);
      return ir_r_set(1.0 - x_fraction);
    });
  });

}).call(this);
